### PR TITLE
Add authorization rules[Enhancements and Bug Fixes for CanCanCan Integration]

### PR DESCRIPTION
**Pull request by stino-x**
Screenshot 2023-12-02 004645
Description:

Dear  Reviewer,

I hope this message finds you well. I've been working on improving the integration of CanCanCan into our project, and I'm excited to submit this pull request for your review. These changes aim to enhance the authorization logic, fix some bugs, and ensure a smoother user experience.

Changes Made:

Improved Authorization Logic:

[Brief description of the improvements made in terms of authorization logic.]
Bug Fixes:

[List of specific bugs addressed and how they were resolved.]
Enhanced Readability and Documentation:

[Any changes made to improve code readability or add/update documentation.]
Testing:

I have thoroughly tested these changes in both development and staging environments. The existing test suite has been extended to cover the new functionality and ensure that the bug fixes have been successfully implemented.

**I appreciate your time and consideration in reviewing these changes. If there are any further adjustments needed or if you have any questions, please don't hesitate to let me know. I'm eager to contribute to the improvement of our project.

Thank you!

Best regards,
Iheagwara Augustine**

### CODE REVIEW

**Review by skyv26 — COMMENTED** [review]
## Hi @stino-x,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🟨 



## Reason 🗒️ 
You have submitted a project, that doesn't have the contribution from your `pair-programming` partner OR if you were working solo this week then add the screen-shot from student-success.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

#### Cheers, and Happy coding!👏👏👏

## ⚠️  WARNING ⚠️ 
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   @skyv26
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   linkedin-skyv2022
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   @vrma_aakash
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   @skybrel
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   @skybrel
</a>

</td>
</tr>
</table>

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by stino-x** [comment]
HI I AM LITERALLY THE ONLY PERSON THIS WEEK I HAVE  NO PARTNERS ANYWHERE

**Comment by Abenezer-Tilahun** [comment]
Hello @stino-x could add the screenshot of your dashboard for the Collaboration Info to check your the only one assigned in these week.

**Comment by stino-x** [comment]
check now please

**Comment by skyv26** [comment]
@stino-x submit your project for review again

**Comment by stino-x** [comment]
it still says review pending i dont know if someone is reviewing it

**Review by Abenezer-Tilahun — APPROVED** [review]
Hi @stino-x 
 
Your project is complete  👍 💯   There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 👏🏻

✅ No linter errors.
✅ You used correct Git-Flow.
✅ Professional README  
✅ Good Commit Messages.
✅ You used CanCanCan gem as required 👍🏽
✅ Registration and Login features work fine as expected 👍🏽
✅ Correctly Use CanCanCan for this authorization.
✅ Good job for Implemented Blog app: add authorization rules.

## Optional suggestions 
 
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

**Pull request merged**
